sudo: required
language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install -q youtube-dl

script:
  - wget -q https://github.com/fabianonline/telegram.sh/raw/master/telegram && chmod +x telegram
  - chmod +x *.sh
  - ./script.sh 

notifications:
  email:
    on_success: never
    on_failure: always
