sudo: required

services:
  - docker

before_install:
  - git clone https://github.com/ninetrackers/zad.git -b yt zad/
  # Pull docker images
  - docker pull vimagick/youtube-dl

script:
  - wget -q https://github.com/yshalsager/telegram.sh/raw/master/telegram && chmod +x telegram
  - chmod +x *.sh
  - ./script.sh 

notifications:
  email:
    on_success: never
    on_failure: always
